version: '3'

services:

  nginx-api-demo:
    build: . # build from Dockerfile in the current directory
    network_mode: host
    # restart: always
    ports:
      - 80:80
      - 8082:8082
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./script:/etc/nginx/script
      - ./html:/usr/share/nginx/html
      